CREATE TABLE board
(
  no INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  writer VARCHAR(30) NOT NULL,
  title VARCHAR(40) NOT NULL,
  content VARCHAR(210) NOT NULL,
  password VARCHAR(21) NOT NULL,
  hidden_fl BOOLEAN DEFAULT FALSE NOT NULL
);
